bookshop/authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url('login/', authapp.login, name='login'),
    url('logout/', authapp.logout, name='logout'),
    url('register/', authapp.register, name='register'),
    url('edit/', authapp.edit, name='edit')
]

bookshop/basketapp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'basketapp'


urlpatterns = [
    path('add/<int:pk>/', views.add_to_basket, name='add'),
    path('remove/<int:pk>/', views.remove_from_basket, name='remove'),
    url('', views.basket, name='basket_view'),
]

bookshop/bookshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp.views import index_view
from mainapp.views import contacts_view
from mainapp.views import product_view
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from mainapp.endpoints import BookModelSet

router = DefaultRouter()
router.register('books', BookModelSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='index'),
    # path('book/', product_view, name='product'),
    path('', include('mainapp.urls')),
    path('contacts/', contacts_view, name='contacts'),
    url('auth/', include('authapp.urls', namespace='auth')),
    url('orders/', include('basketapp.urls', namespace='orders')),
    path('api/', include(router.urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookshop/basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Book


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='Количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='Время добавления', auto_now_add=True)

    def __str__(self):
        return str(self.user)

    def _get_product_price(self):
        return self.book.price * self.quantity

    product_price = property(_get_product_price)

    def _get_total_quantity(self):
        _items = Basket.objects.filter(user=self.user)
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))

        return _totalquantity

    total_quantity = property(_get_total_quantity)

    def _get_total_price(self):
        _items = Basket.objects.filter(user=self.user)
        _totalprice = sum(list(map(lambda x: x.product_price, _items)))
        return _totalprice

    total_price = property(_get_total_price)






# Create your models here.

bookshop/basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Basket
from mainapp.models import Book


@login_required
def basket(request):
    basket_items = Basket.objects.filter(user=request.user).order_by('book__category')
    return render(request, 'basketapp/basket.html', {'basket_items': basket_items})


@login_required
def add_to_basket(request, pk):

    book = get_object_or_404(Book, id=pk)
    old_basket_item = Basket.objects.filter(user=request.user, book=book)

    if old_basket_item:
        old_basket_item[0].quantity += 1
        old_basket_item[0].save()

    else:
        new_basket_item = Basket(user=request.user, book=book)
        new_basket_item.quantity += 1
        new_basket_item.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def remove_from_basket(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

bookshop/basketapp/templates/basketapp/basket.html
<!doctype html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <link rel="icon" href="favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Arimo:400,400i,700,700i&amp;subset=cyrillic" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">


    <title>{% block title %}
            {% endblock %}</title>
</head>

<body>

{% block preheader %}
    <header>
        <div class="container">

            <div class="row my-3">
                <div class="col-md-2 d-flex flex-column justify-content-start">
                    <div class="left-corner-dots"></div>
                </div>
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-2 text-center"><a href="/contacts/" class="btn btn-link">Контакты</a></div>
                        <div class="col-md-3"><a href="" class="btn btn-link">+7(812)999-99-99</a></div>
                        <div class="col-md-3"><a href="{% url 'orders:basket_view' %}" class="btn btn-link"> Мои покупки</a></div>
                        <div class="col-md-2"><a href="{% url 'auth:edit' %}" class="btn btn-link">{{ user.username }}</a></div>
                        <div class="col-md-2 text-right">
                            {% if user.is_authenticated %}
                                <a href="{% url 'auth:logout' %}" class="btn-primary btn">Выйти</a>
                            {% else %}
                                 <a href="{% url 'auth:login' %}" class="btn-primary btn">Войти</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-11">
                <div class="logo-link"><a href="../"><img src="../static/img/blue-logo.png"></a></div>
                <div class="navbar">
                    <div class="navbar-links-search">
                        <div>
                            <div class="form-row align-items-center">
                            <div style="margin-top: -10px;">
                                <div class="input-group search-input radius-100">
                                        <input type="text" class="form-control" value="Поиск">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><img src="../static/img/search-icon.svg" alt="" height="20"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
            </div>





        </div>
    </header>
{% endblock %}



<main role="main">
    <div class="container-fluid basket-items">
        <div class="row">
            <div class="col-md-12">
                 {% block content %}
                    <div class="basket-list">
                        {% for item in basket_items %}
                            <div class="basket-record">
                                <div>{{ item.book.name}}</div>
                                <div>{{ item.book.author}}</div>
                                <div>{{ item.book.price }} руб</div>
                                <div>{{ item.book.price }}</div>
                                <div>{{ item.quantity }}</div>
                                <div>{{ item.price }}</div>
                                <button class="btn btn-round">
                                    <a href="{% url 'orders:remove' item.pk %}"> Удалить </a>
                                </button>
                            </div>
                        {% endfor %}
                    </div>
                {% endblock %}
            </div>
        </div>
    </div>
</main>

<footer class="text-muted">
    <div class="container d-flex flex-row justify-content-space-between"> 
        <ul>
            <li><a href="contacts.html">Контакты</a></li>
            <li><a href="#">Доставка</a></li>
            <li><a href="#">Возврат товара</a></li>
        </ul>
        <div>+78129999999</div>
    </div>
</footer>

{% block page_js %}
{% endblock %}
</body>
</html>