bookshop/authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url('login/', authapp.login, name='login'),
    url('logout/', authapp.logout, name='logout'),
    url('register/', authapp.register, name='register'),
    url('edit/', authapp.edit, name='edit')
]

bookshop/basketapp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'basketapp'


urlpatterns = [
    path('add/<int:pk>/', views.add_to_basket, name='add'),
    path('remove/<int:pk>/', views.remove_from_basket, name='remove'),
    url('', views.basket, name='basket_view'),
]

bookshop/bookshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp.views import index_view
from mainapp.views import contacts_view
from mainapp.views import product_view
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from mainapp.endpoints import BookModelSet

router = DefaultRouter()
router.register('books', BookModelSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='index'),
    # path('book/', product_view, name='product'),
    path('', include('mainapp.urls')),
    path('contacts/', contacts_view, name='contacts'),
    url('auth/', include('authapp.urls', namespace='auth')),
    url('orders/', include('basketapp.urls', namespace='orders')),
    path('api/', include(router.urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookshop/mainapp/urls.py
from django.urls import path
from . import views
from . import endpoints

app_name = 'product'

# endpoints = [
#     path('api/', endpoints.api_product_list, name='api_list'),
# ]

urlpatterns = [
    path('', views.index_view, name='index'),
    path('<int:pk>/', views.product_view, name='detail')
]

bookshop/mainapp/models.py
from django.db import models


class Category(models.Model):

    name = models.CharField(max_length=150, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return self.name


class Book(models.Model):

    name = models.CharField(max_length=150)
    author = models.CharField(max_length=150)
    price = models.IntegerField()
    page_amount = models.IntegerField(null=True)
    publisher = models.CharField(max_length=150)
    description = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to='.')
    in_stock = models.BooleanField(default=True, verbose_name='В наличии')
    category = models.ForeignKey('mainapp.Category', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return self.name

bookshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from basketapp.models import Basket
from .models import Book
from .models import Category


bestsellers = get_list_or_404(Book)
new_books = get_list_or_404(Book)
links_menu = get_list_or_404(Category)


def basket_items(request):

    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    return basket


def index_view(request):

    basket = basket_items(request)

    return render(request, 'mainapp/index.html', {'content': [bestsellers, new_books, links_menu, basket]})


def contacts_view(request):

    basket = basket_items(request)

    return render(request, 'mainapp/contacts.html', {'content': [bestsellers, new_books, links_menu, basket]})


def product_view(request, pk=None):

    book = get_object_or_404(Book, id=pk)
    similar_books = get_list_or_404(Book)

    basket = basket_items(request)

    return render(request, 'mainapp/product.html', {'content': [book, similar_books, links_menu, basket]})

bookshop/mainapp/templates/mainapp/base.html
<!doctype html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <link rel="icon" href="favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Arimo:400,400i,700,700i&amp;subset=cyrillic" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>

    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B"-->
    <!--crossorigin="anonymous">-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
    crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>


    <title>{% block title %}
            {% endblock %}</title>
</head>

<body>

{% block preheader %}
    <header>
        <div class="container">

            <div class="row my-3">
                <div class="col-md-2 d-flex flex-column justify-content-start">
                    <div class="left-corner-dots"></div>
                </div>
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-2 text-center"><a href="/contacts/" class="btn btn-link">Контакты</a></div>
                        <div class="col-md-3"><a href="" class="btn btn-link">+7(812)999-99-99</a></div>
                        <div class="col-md-3"><a href="{% url 'orders:basket_view' %}" class="btn btn-link"> Мои покупки ( {{ content.3.0.total_quantity}} )</a></div>
                        <div class="col-md-2"><a href="{% url 'auth:edit' %}" class="btn btn-link">{{ user.username }}</a></div>
                        <div class="col-md-2 text-right">
                            {% if user.is_authenticated %}
                                <a href="{% url 'auth:logout' %}" class="btn-primary btn">Выйти</a>
                            {% else %}
                                 <a href="{% url 'auth:login' %}" class="btn-primary btn">Войти</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}


{% block header %}
{% endblock %}


<main role="main">
    {% block content %}
    {% endblock %}
</main>

<footer class="text-muted">
    <div class="container d-flex flex-row justify-content-space-between"> 
        <ul>
            <li><a href="contacts.html">Контакты</a></li>
            <li><a href="#">Доставка</a></li>
            <li><a href="#">Возврат товара</a></li>
        </ul>
        <div>+78129999999</div>
    </div>
</footer>

{% block page_js %}
{% endblock %}
</body>
</html>

bookshop/mainapp/templates/mainapp/contacts.html
{% extends "mainapp/base.html" %}

{% load staticfiles %}

{% block title%}
Главная - Социофобия на виражах
{% endblock %}

{% block header %}
<header class="container">
    <div class="container-fluid h100">
        <div class="row h100">
            <div class="col-md-1 d-flex flex-column justify-content-end">

            </div>
            <div class="col-md-11">
                <div class="logo-link"><a href="../"><img src="{% static '/img/blue-logo.png' %}"></a></div>
                <div class="navbar">
                    <div class="navbar-links-search">
                        <div></div>
                        <div>
                            <form>
                            <div class="form-row align-items-center">
                            <div style="margin-top: -10px;">
                                <div class="input-group search-input radius-100">
                                        <input type="text" class="form-control" value="Поиск">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><img src="../static/img/search-icon.svg" alt="" height="20"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

{% endblock %}

{% block content %}
    <div class="album py-5">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-10 d-flex justify-content-space-between">
                    <div class="col-md-8">
                        <div class="contacts">
                            <p><h2>Адрес:</h2> СПб, ул. Пушкина, дом Колотушкина, 199900 </p>
                            <p><h2>Телефон:</h2> +7 812 999 99 99</p>
                            <p><h2>Режим работы:</h2> ПН-ПТ, 10-20</p>
                            <p><h2>Как добраться:</h2></p>
                            <div class="row">
                                <div class="column-md-12">
                                    <div class="map">
                                    <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A4d2ea36ad176cd6711dbc56615755f5f6cd6e3fb173946f8583bf19615e4b322&amp;width=900&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

bookshop/mainapp/templates/mainapp/inc_category_menu.html
{% block category-menu %}
<ul ​class​="​links​-​menu​">
        {% for link in content.2 %}
            <li><a href=""> {{ link.name|upper }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

bookshop/mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}

{% load staticfiles %}

{% block title%}
Главная - Социофобия на виражах
{% endblock %}

{% block preheader %}
    <header>
        <div class="container">
            <div class="row my-3">
                <div class="col-md-2">
                </div>
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-2 text-center"><a href="contacts/" class="btn btn-link">Контакты</a></div>
                        <div class="col-md-3"><a href="" class="btn btn-link">+7(812)999-99-99</a></div>
                        <div class="col-md-3"><a href="{% url 'orders:basket_view' %}" class="btn btn-link"> Мои покупки ( {{ content.3.0.total_quantity}} )</a></div>
                        <div class="col-md-2"><a href="{% url 'auth:edit' %}" class="btn btn-link">{{ user.username }}</a></div>
                        <div class="col-md-2 text-right">
                            {% if user.is_authenticated %}
                                <a href="{% url 'auth:logout' %}" class="btn-primary btn">Выйти</a>
                            {% else %}
                                 <a href="{% url 'auth:login' %}" class="btn-primary btn">Войти</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block header %}
<header class="welcome-block">
    <div class="container-fluid h100">
        <div class="row h100">
            <div class="col-md-2 d-flex flex-column justify-content-end">
                <form>
                    <div class="form-row align-items-center">
                        <div>
                            <div class="input-group search-input radius-100 white-black-gradient">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><img src="{% static 'img/search-icon.svg' %}" alt="" height="20"></div>
                                </div>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-10">
                <section class="text-left">
                    <h1>
                        <small>Книжный магазин</small>
                        <br>Социофобия <br> на виражах
                    </h1>
                </section>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
    <div class="album py-5">
        <div class="container-fluid">

            <div class="row">

                <div class="col-md-2">
                    <div class="row">
                        <div class="sidebar">
                            {% include 'mainapp/inc_category_menu.html'%}
                        </div>
                    </div>
                </div>
                <div class="col-md-10">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Бестселлеры</h3>
                        </div>

                        <div class="row" id="bestsellers">

                        </div>

                    </div>
                </div>


            </div>
            <div class="row">

                <div class="col-md-2">
                </div>
                <div class="col-md-10">
                    <div class="row">

                        <div class="col-md-12">
                            <h3>Новинки</h3>
                        </div>

                        <div class="row" id="new-books">

                        </div>


                    </div>
                </div>


            </div>
        </div>
    </div>

    <div class="products">
        <div id="products-list"></div>
    </div>

    {% block page_js%}
        <script type="text/javascript" src="{% static 'mainapp/index.js'%}"></script>

    <script>
        axios.get('http://127.0.0.1:8000/api/books/')
            .then(renderData)
    </script>
    {% endblock %}
{% endblock %}

bookshop/mainapp/templates/mainapp/product.html
{% extends "mainapp/base.html" %}

{% load staticfiles %}

{% block title %}
{{ content.0.name }} - Социофобия на виражах
{% endblock %}

{% block header %}
<header class="container">
    <div class="container-fluid h100">
        <div class="row h100">
            <div class="col-md-1 d-flex flex-column justify-content-end">

            </div>
            <div class="col-md-11">
                <div class="logo-link"><a href="../"><img src="../static/img/blue-logo.png"></a></div>
                <div class="navbar">
                    <div class="navbar-links-search">
                        <div>{% include 'mainapp/inc_category_menu.html'%}</div>
                        <div>
                            <form>
                            <div class="form-row align-items-center">
                            <div style="margin-top: -10px;">
                                <div class="input-group search-input radius-100">
                                        <input type="text" class="form-control" value="Поиск">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><img src="../static/img/search-icon.svg" alt="" height="20"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                        </div>
                    </div>
                    <h1> {{content.0.name}}</h1>
                    <div class="product-author-name">{{content.0.author}}</div>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block content %}
    <div class="album py-5">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-10 d-flex justify-content-space-between">
                    <div class="col-md-4">
                        <div class="product-photo"><img src={{content.0.image.url}} alt={{content.0.name}}>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 d-flex flex-row justify-content-space-between product-info">
                            <div class="product-info">
                                <table>
                                    <tr>
                                        <td>Кол-во страниц:</td>
                                        <td>{{content.0.page_amount}}</td>
                                    </tr>
                                    <tr>
                                        <td>Издательство:</td>
                                        <td>{{content.0.publisher}}</td>
                                    </tr>
                                    <tr>
                                        <td>Год издания:</td>
                                        <td>{{content.0.year}}</td>
                                    </tr>
                                </table>
                            </div>
                            <div><button class="yellow-buy-btn" type="submit">
                                <a href="{% url 'orders:add' pk=content.0.id %}">{{content.0.price}}</a>
                                </button></div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <p>{{content.0.description}} </p>
                            </div>
                            <div class="col-md-4"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                </div>
                <div class="col-md-10">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>С этой книгой покупают:</h3>

                        </div>
                        {% for book in content.1 %}
                            <div class="col-md-3">
                                <div class="card mb-4 box-shadow text-center bordered">
                                    <a href="{% url 'product:detail' book.id %}"><img src={{book.image.url}} alt="Card image cap"></a>
                                    <div class="card-body">
                                        <p class="book-name"><a href="{% url 'product:detail' book.id %}">{{book.name}}</a></p>
                                         <p class="author-name"><a href="c">{{book.author}}</a></p>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <a href="">
                                                <small class="price-catalog">{{book.price}}</small>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}