bookshop/authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url('login/', authapp.login, name='login'),
    url('logout/', authapp.logout, name='logout'),
    url('register/', authapp.register, name='register'),
    url('edit/', authapp.edit, name='edit')
]

bookshop/bookshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp.views import index_view
from mainapp.views import contacts_view
from mainapp.views import product_view
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from mainapp.endpoints import BookModelSet

router = DefaultRouter()
router.register('books', BookModelSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='index'),
    # path('book/', product_view, name='product'),
    path('', include('mainapp.urls')),
    path('contacts/', contacts_view, name='contacts'),
    url('auth/', include('authapp.urls', namespace='auth')),
    url('orders/', include('basketapp.urls', namespace='orders')),
    path('api/', include(router.urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookshop/authapp/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

class ShopUser(AbstractUser):
    userpic = models.ImageField(upload_to='userpics', blank=True)
    age = models.PositiveIntegerField(verbose_name='age', null=True)

# Create your models here.

bookshop/authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name


class ShopUserRegistrationForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password1', 'password2', 'email', 'age', 'userpic')

    def __init__(self, *args, **kwargs):
        super(ShopUserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password', 'email', 'age', 'userpic')

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

            if field_name == 'password':
                field.widget = forms.HiddenInput()

bookshop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import ShopUserLoginForm, ShopUserRegistrationForm, ShopUserEditForm
from django.contrib import auth
from django.urls import reverse


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
            return HttpResponseRedirect(reverse('/register'))
    else:
        login_form = ShopUserLoginForm()
        content = {}
        content['login_form'] = login_form
        return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    if request.method == 'POST':
        register_form = ShopUserRegistrationForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegistrationForm()

    content = {'register_form': register_form}

    return render(request, 'authapp/register.html', content)


def edit(request):
    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    content = {'edit_form': edit_form}

    return render(request, 'authapp/edit.html', content)

bookshop/authapp/templates/authapp/base.html
{% load staticfiles %}
<html lang="en">

<link href="https://fonts.googleapis.com/css?family=Arimo:400,400i,700,700i&amp;subset=cyrillic" rel="stylesheet">

<!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{% static 'css/style.css' %}" rel="stylesheet">

<head>
    <meta charset="UTF-8">
    <title>
        {%block title%}
        {% endblock %}
    </title>
</head>

<body>
    {% block content %}
    {% endblock%}
</body>
</html>

bookshop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block title %}
<p>Изменить учетную запись</p>
{% endblock%}

{% block content %}
    <div class="container-fluid">
        <form class="" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ edit_form.as_p }}
            <br>
            <input class="btn-primary btn" type="submit" value="Сохранить">
        </form>
        <button class="btn btn-round last">
            <a href="{% url 'index' %}" class=""> На главную</a>
        </button>
        <div class="userpic">
            <img src="/media/{{ user.userpic }}">
        </div>
    </div>
{% endblock %}

bookshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block title %}
Войти
{% endblock%}

{% block content %}
    <div class="registration-form">
        <div class="registration-container">
            <form class="" action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}
                {{ login_form.as_p }}
                <br>
                <input class="btn-primary btn" type="submit" value="Войти">
            </form>
            <button class="btn">
                <a href="{% url 'auth:register' %} class='' "> Зарегистрироваться</a>
            </button>
        </div>
    </div>
{% endblock %}

bookshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block title %}
<p>Зарегистрироваться</p>
{% endblock%}

{% block content %}
    <div class="container-fluid">
        <form class="'form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ register_form.as_p }}
            <br>
            <input class="form-control btn-primary btn" type="submit" value="Зарегистрироваться">
        </form>
    </div>
{% endblock %}